<script runat="server">

    Protected Sub Button1_Click(sender As Object, e As EventArgs)

    End Sub
</script>
<form id="form1" runat="server" aria-sort="none">
    <h1 style="text-align: center">Продажа мониторов</h1>

    <asp:GridView ID="GridView1" width="600" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Код" DataSourceID="SqlDataSource1" BackColor="White" BorderColor="#E7E7FF" BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Horizontal" style="text-align: center" HorizontalAlign="Center">
        <AlternatingRowStyle BackColor="#F7F7F7" />
        <Columns>
            <asp:BoundField DataField="Код" HeaderText="Код" InsertVisible="False" ReadOnly="True" SortExpression="Код" />
            <asp:BoundField DataField="Модель" HeaderText="Модель" SortExpression="Модель" />
            <asp:BoundField DataField="Диагональ" HeaderText="Диагональ" SortExpression="Диагональ" />
            <asp:BoundField DataField="Страна" HeaderText="Страна" SortExpression="Страна" />
            <asp:BoundField DataField="Цена" HeaderText="Цена" SortExpression="Цена" />
        </Columns>
        <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
        <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
        <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
        <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
        <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
        <SortedAscendingCellStyle BackColor="#F4F4FD" />
        <SortedAscendingHeaderStyle BackColor="#5A4C9D" />
        <SortedDescendingCellStyle BackColor="#D8D8F0" />
        <SortedDescendingHeaderStyle BackColor="#3E3277" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT [Код], [Модель], [Диагональ], [Страна], [Цена] FROM [Display]" DeleteCommand="Delete from Display Where Код=@Код" UpdateCommand="UPDATE [Display] SET [Модель] = @Модель, [Диагональ] = @Диагональ, [Страна] = @Страна, [Цена] = @Цена Where [Код] = @Код"></asp:SqlDataSource>
    <asp:Table ID="Table1" runat="server" width="600" HorizontalAlign="Center">
        <asp:TableRow>
            <asp:TableCell>
                <asp:Button ID="Button2" runat="server" Text="Добавить запись" style="margin-left: 0px" width="200"/>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox ID="TextBox5" runat="server" width="120"></asp:TextBox>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox ID="TextBox6" runat="server" width="80"></asp:TextBox>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox ID="TextBox7" runat="server" width="80"></asp:TextBox>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox ID="TextBox8" runat="server" width="80"></asp:TextBox>
            </asp:TableCell>
        </asp:TableRow>
    </asp:Table>
                    <asp:Button ID="Button1" runat="server" Text="Добавить запись" style="margin-left: 0px" width="200" onserverclick="Button_Click1" OnClick="Button1_Click"/>

</form>

